name: Lint GitHub Actions workflows
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    uses: devops-actions/.github/.github/workflows/actionlint.yml@e537f6767594e8d4cfff18edf24e5b4e899b0e51 # main
    permissions:
      contents: read
      pull-requests: write
