name: Submit Actions Dependencies
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Weekly
permissions:
  contents: read

jobs:
  submit-dependencies:
    uses: devops-actions/.github/.github/workflows/actions-dependencies.yml@686cfb7424be0c32c8fe4e9e335f4500c5e9978c # main
    permissions:
      contents: write # Required to read workflow files
      id-token: write # Required for dependency submission
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
