name: "Approve Dependabot PR's" 
on:
  pull_request:

permissions:
  contents: read

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
      actions: write
    uses: devops-actions/.github/.github/workflows/approve-dependabot-pr.yml@32339973f79273aa46e37f663e6b9bef0dd2fcd3 # main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
