name: "Approve Dependabot PR's" 
on:
  pull_request:

permissions:
  contents: read

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
      actions: write
    uses: devops-actions/.github/.github/workflows/approve-dependabot-pr.yml@e537f6767594e8d4cfff18edf24e5b4e899b0e51 # main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
